# Generated by Django 2.2 on 2019-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tofes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
