# Generated by Django 2.2 on 2019-05-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tofes', '0004_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=512)),
                ('fname', models.CharField(max_length=512)),
                ('inputage', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
