# Generated by Django 2.2 on 2019-05-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tofes', '0005_entry1'),
    ]

    operations = [
        migrations.CreateModel(
            name='resnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
