# Generated by Django 2.2 on 2019-05-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tofes', '0006_resnum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry1',
            new_name='Entry',
        ),
        migrations.DeleteModel(
            name='resnum',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='inputage',
            new_name='input_age',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='name1',
            new_name='last_name',
        ),
    ]
