# Generated by Django 2.2 on 2019-05-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tofes', '0003_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
